language: ruby
sudo: false
rvm: 2.2
cache: bundler
branches:
  only:
  - master
git:
  depth: 3
script:
  - bundle exec jekyll build --source docs --destination docs/_site
  - bundle exec htmlproofer ./docs/_site --check-html --check-sri --disable-external
  - gem build smooth-jekyll-theme.gemspec