language: ruby
sudo: false
rvm: 2.2
cache: bundler

branches:
  only:
  - master

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --check-html --check-sri --disable-external
  - gem build smooth-jekyll-theme.gemspec