language: ruby
sudo: false
rvm: 2.2

branches:
  only:
  - master
cache:
  bundler: true
  directories:
    - vendor/bundle

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --check-html --check-sri --disable-external
  - gem build smooth-jekyll-theme.gemspec