# site configuration
lang: zh-CN # site's language, default to en-US
title: Smooth
favicon: /assets/img/favicon-32x32.png # the relative url of the favicon
brand_icon: /assets/img/brand-icon.svg # the relative url of the icon to be displayed in page header