#!/bin/sh
#reference: https://github.com/pages-themes/cayman

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri --disable-external
bundle exec script/validate-html
gem build smooth-jekyll-theme.gemspec
